branch-defaults:
  default:
    environment: seng3011-turtle
    group_suffix: null
  master:
    environment: seng3011-turtle
environment-defaults:
  seng3011-turtle:
    branch: null
    repository: null
global:
  application_name: seng3011-flask
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.6
  default_region: ap-southeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application

packages:
  yum:
    libjpeg-devel: '6b'
